name: Deploy Widgets to Mainnet - Devhub
on:
  pull_request:
  push:
    branches: [main]
jobs:
  deploy-widgets:
    runs-on: ubuntu-latest
    name: Deploy ( or diff from PR ) - Devhub
    environment: devhub.near
    defaults:
      run:
        working-directory: ./instances/devhub.near
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set replacements
        id: set_replacements
        run: |
          echo "replacements=$(jq -r '[to_entries[] | .["find"] = "${" + .key + "}" | .["replace"] = .value | del(.key, .value), {"find": "${REPL_POSTHOG_API_KEY}", "replace": "'${{ secrets.POSTHOG_API_KEY }}'"}]' aliases.mainnet.json | tr -d "\n\r")" >> $GITHUB_OUTPUT

      - name: Replace placeholders
        uses: flcdrg/replace-multiple-action@v1
        with:
          files: "**/*.jsx"
          find: "${{ steps.set_replacements.outputs.replacements }}"
          prefix: "(^|.*)"
          suffix: "($|.*)"

      - name: Install dependencies
        run: |
          npm ci
          curl --proto '=https' --tlsv1.2 -LsSf https://github.com/FroVolod/bos-cli-rs/releases/download/v0.3.6/bos-cli-installer.sh | sh

      - name: Deploy widgets
        run: |
          BRANCH="$(git rev-parse --abbrev-ref HEAD)"
          echo "on branch $BRANCH"
          if [[ "$BRANCH" != "main" ]]; then
            echo "Not on main branch, dry run by diff with devhub.near"
            npm run dry-run:devhub
          else
            bos components deploy '${{ vars.NEAR_SOCIAL_ACCOUNT_ID }}' sign-as '${{ vars.NEAR_SOCIAL_ACCOUNT_ID }}' network-config mainnet sign-with-plaintext-private-key --signer-public-key '${{ vars.NEAR_SOCIAL_ACCOUNT_PUBLIC_KEY }}' --signer-private-key '${{ secrets.NEAR_SOCIAL_ACCOUNT_PRIVATE_KEY }}' send
          fi
